### ISSUE TITLE
Failed to map segment from shared object: Operation not permitted

### ISSUE THREAD

**Issue by Crispy1975** [marcominetti/node-memwatch#11]
Hi,

We're running `memwatch` in a few places, this problem has only come up on once server (Ubuntu 14.04 LTS), the full error when running our app is...

```shell
Error: /home/ubuntu/src/app/node_modules/memwatch-next/build/Release/memwatch.node: failed to map segment from shared object: Operation not permitted
```

Searching around this seems to crop up mostly when `/tmp` is `noexec` but I do not think this is the case due to other systems running this fine. Only difference here is we have a partition mounted with all the source code on.

Any ideas?

**Comment by faustomorales** [comment]
I had this exact same problem because I was running my app from a mounted partition. I had added the users option to my fstab, which implies noexec unless you set the exec option explicitly. I added exec to the end of the fstab line and everything started working again.
