### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by djanowski** [marcominetti/node-memwatch#27]
Ciao @marcominetti! Thanks for your great work.

Is the project still maintained? If not, maybe some other people are willing to collaborate? I saw @srowatt made interesting progress.

(Specifically I'm seeing a crash on 6.9.4 when using HeapDiff, but posting this meta-issue first as I see other issues haven't been responded to. Thank you.)

**Comment by srowatt** [comment]
Hi @djanowski , I've tried running the tests against 6.9.4 and it didn't crash. The test cases only do a basic set of tests so if you could supply any details on how you got it to crash I'll look into it.

**Comment by djanowski** [comment]
@srowatt 👋 I created #28 detailing the error. The same happens with `memwatch-ng` btw. Thanks!

**Comment by marcominetti** [comment]
I'm going to be back at maintaining this module next month as dependecy for another project... But yes, if others want to collaborate would be great... @srowatt may I add you as collaborator here?

**Comment by marcominetti** [comment]
@srowatt done, if you need to push directly here

**Comment by srowatt** [comment]
@marcominetti - I'll try to debug the issue and create a PR if I fix it.

**Comment by djanowski** [comment]
Thanks @marcominetti for the quick reply and for taking action; thanks @srowatt for looking into the issue!
