### ISSUE TITLE
Issue with node 7.4.0

### ISSUE THREAD

**Issue by cyanic-webdesign** [marcominetti/node-memwatch#30]
Is there an issue with building with node 7.4.0? I'm getting the next error when trying to build:

`Error: Error relocating /opt/service/node_modules/memwatch-next/build/Release/memwatch.node: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi: symbol not found`

**Comment by srowatt** [comment]
Are you using an Alpine Linux image to do the build on?

**Comment by cyanic-webdesign** [comment]
Yes, we use Alpine

**Comment by cyanic-webdesign** [comment]
Nevermind, it was an issue on our side. We used different node versions to build and deply.
